name: Build and Deploy Code

on: [push, pull_request]

jobs: 
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v4
      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: upgrade pip
        run: python -mpip install --upgrade pip
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: run tests
        run: pytest
      - name: build and deploy
        