name: Build and Deploy Code

on: [push, pull_request]

jobs: 
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling ghit repo
        uses: actions/checkout@v4
      - name: say hi to danielle
        run: echo "Hello, Danielle!"
        